#!/bin/bash

if [ $# -eq 0 ]; then
  echo "This script removes files and directories extracted from a given tar-file (or corresponding to the listing of that archive)."
  echo "Usage:"
  echo "rmuntared original.tar optionally_dir_with_extracted_files_if_not_in_the_current_dir"
  exit 1
fi

TAR_FILE="$1"

if [ -z "$2" ]; then
  DIR="./"
else
  DIR="$2"
fi

FILES_FROM_TAR=$(tar -tf $TAR_FILE)

for file in $FILES_FROM_TAR; do
  if [ -e "$DIR/$file" ]; then
    rm -rf "$DIR/$file"
  fi
done
